version: '3.8'

services:
  whisper-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5555:5555"
    environment:
      - FLASK_ENV=development
      - DEBUG=true
      - WHISPER_MODEL=tiny
      - LANGUAGE=pt
      - MAX_FILE_SIZE=10485760
      - LOG_LEVEL=DEBUG
    volumes:
      - ../src:/app/src:ro
      - ../logs:/app/logs
      - ../tests:/app/tests:ro
      - whisper_cache:/home/whisper/.cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/health"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - whisper_network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - whisper-api
    networks:
      - whisper_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - whisper_network

volumes:
  whisper_cache:
  redis_data:

networks:
  whisper_network:
    driver: bridge 